name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      TOKEN_SECRET: ${{ TOKEN_SECRET }}
      D_HOST: ${{ secrets.D_HOST }}
      D_USER: ${{ secrets.D_USER }}
      D_PASSWORD: ${{ secrets.D_PASSWORD }}
      D_DATABASE: ${{ secrets.D_DATABASE }}
      D_DBPORT: ${{ secrets.D_DBPORT }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: login to Dockerhub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: create docker-compose stack
        run: docker-compose up -d
      - name: check docker containers
        run: docker ps
      - name: change docker image
        run: docker image tag node:latest rainerbonilla/type-node-api:latest
      - name: push image to dockerhub
        run: docker push rainerbonilla/type-node-api:latest
